openapi: 3.0.3
info:
  title: Product API
  version: 1.0.0
  description: >
    API for managing and retrieving product data.
    Provides endpoints for fetching all products and related products for the main page.

servers:
  - url: https://api.example.com
    description: Main API server

tags:
  - name: Products
    description: Endpoints related to product listing and product data retrieval.

paths:
  /products:
    get:
      tags:
        - Products
      summary: Get all products list
      description: Retrieve a list of all available products.
      responses:
        "200":
          description: Successful response with product list
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
        "400":
          description: Bad request — invalid parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found — resource unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /relatedProducts:
    get:
      tags:
        - Products
      summary: Related Products for Main page
      description: Retrieve related products displayed on the main page.
      responses:
        "200":
          description: Successful response with related product list
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
        "400":
          description: Bad request — invalid parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not found — resource unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: "12345"
        name:
          type: string
          example: "T-shirt"
        image:
          type: string
          example: "https://example.com/images/tshirt.jpg"
        description:
          type: object
          properties:
            caption:
              type: string
              example: "Stylish cotton T-shirt"
            small:
              type: string
              example: "Short description of product"
            full:
              type: string
              example: "Detailed information about product, material, and size chart"
        price:
          type: number
          example: 29.99
        currency:
          type: string
          example: "USD"
        discount:
          type: object
          properties:
            new:
              type: boolean
              example: false
            discount:
              type: number
              example: 10
            last:
              type: boolean
              example: false
            hot:
              type: boolean
              example: false
        category:
          type: string
          example: "Clothing"
        size:
          type: array
          items:
            type: string
            enum: [XS, S, M, L, XL]
        color:
          type: array
          items:
            type: string
            example: "red"
        rating:
          type: number
          format: float
          example: 4.5

    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: error
        code:
          type: integer
          example: 400
        message:
          type: string
          example: Invalid request parameters
